departamentos_data = {
    "departamentos": [
        {
            "id": 1,
            "nombre": "Amazonas",
            "ciudades": [
                "Leticia",
                "Puerto Nariño",
                "El Encanto",
                "La Chorrera",
                "La Pedrera",
                "La Victoria",
                "Mirití-Paraná",
                "Puerto Alegría",
                "Puerto Arica",
                "Puerto Santander",
                "Tarapacá"
            ]
        },
        {
            "id": 2,
            "nombre": "Antioquia",
            "ciudades": [
                "Medellín",
                "Bello",
                "Copacabana",
                "Caldas",
                "Envigado",
                "Girardota",
                "Itagüí",
                "Sabaneta",
                "La Estrella",
                "Barbosa",
                "Rionegro",
                "La Ceja",
                "El Retiro",
                "Abejorral",
                "Sonsón",
                "San Vicente",
                "Marinilla",
                "Guarne",
                "Carmen de Viboral",
                "El Santuario",
                "San Carlos",
                "San Francisco",
                "San Luis",
                "San Rafael",
                "Yarumal",
                "Santa Rosa de Osos",
                "Amalfi",
                "Segovia",
                "Caucasia",
                "Necoclí",
                "Turbo",
                "Apartadó",
                "Carepa",
                "Chigorodó",
                "Urrao",
                "Andes",
                "Jardín",
                "Jericó",
                "Támesis",
                "Valparaíso",
                "Venecia",
                "Fredonia",
                "Heliconia",
                "Santa Fe de Antioquia",
                "San Jerónimo",
                "Anorí",
                "Cisneros",
                "Donmatías",
                "Entrerríos",
                "Girardota",
                "San Pedro de los Milagros",
                "Sopetrán",
                "Yolombó",
                "Angostura",
                "Belmira",
                "Briceño",
                "Campamento",
                "Carolina del Príncipe",
                "Gómez Plata",
                "Guadalupe",
                "Ituango",
                "San Andrés de Cuerquía",
                "Santa Rosa de Osos",
                "Toledo",
                "Valdivia",
                "Yalí",
                "Yolombó",
                "Zaragoza",
                "Cáceres",
                "Tarazá",
                "El Bagre",
                "Nechí",
                "Puerto Berrío",
                "Puerto Nare",
                "Puerto Triunfo",
                "Yondó",
                "Anzá",
                "Remedios",
                "San Roque",
                "Segovia",
                "Vegachí",
                "Buriticá",
                "Cañasgordas",
                "Dabeiba",
                "Ebéjico",
                "Frontino",
                "Liborina",
                "Peque",
                "Sabanalarga",
                "San Jerónimo",
                "Sopetrán",
                "Uramita",
                "Abriaquí",
                "Argelia",
                "Caramanta",
                "Concordia",
                "Fredonia",
                "Hispania",
                "Jardín",
                "Pueblorrico",
                "Salgar",
                "Támesis",
                "Titiribí",
                "Urrao"
            ]
        },
        { "id": 3, "nombre": "Arauca", "ciudades": ["Arauca", "Arauquita", "Cravo Norte", "Fortul", "Puerto Rondón", "Saravena", "Tame"] },
        {
            "id": 4,
            "nombre": "Atlántico",
            "ciudades": [
                "Barranquilla",
                "Baranoa",
                "Campo de la Cruz",
                "Candelaria",
                "Galapa",
                "Juan de Acosta",
                "Luruaco",
                "Malambo",
                "Manatí",
                "Palmar de Varela",
                "Piojó",
                "Polonuevo",
                "Ponedera",
                "Puerto Colombia",
                "Repelón",
                "Sabanagrande",
                "Sabanalarga",
                "Santa Lucía",
                "Santo Tomás",
                "Soledad",
                "Suan",
                "Tubará",
                "Usiacurí"
            ]
        },
        {
            "id": 5,
            "nombre": "Bolívar",
            "ciudades": [
                "Achí",
                "Altos del Rosario",
                "Arenal",
                "Arjona",
                "Arroyohondo",
                "Barranco de Loba",
                "Calamar",
                "Cantagallo",
                "El Carmen de Bolívar",
                "Cartagena de Indias",
                "Cicuco",
                "Clemencia",
                "Córdoba",
                "El Guamo",
                "El Peñón",
                "Hatillo de Loba",
                "Magangué",
                "Mahates",
                "Margarita",
                "María La Baja",
                "Montecristo",
                "Morales",
                "Norosí",
                "Pinillos",
                "Regidor",
                "Río Viejo",
                "San Cristóbal",
                "San Estanislao",
                "San Fernando",
                "San Jacinto",
                "San Jacinto del Cauca",
                "San Juan Nepomuceno",
                "San Martín de Loba",
                "San Pablo",
                "Santa Catalina",
                "Santa Cruz de Mompox",
                "Santa Rosa",
                "Santa Rosa del Sur",
                "Talaigua Nuevo",
                "Tiquisio",
                "Turbaco",
                "Turbaná",
                "Villanueva",
                "Zambrano",
                "Islas del Rosario",
                "Islas de San Bernardo",
                "Isla Fuerte"
            ]
        },
        {
            "id": 6,
            "nombre": "Boyacá",
            "ciudades": [
                "Chíquiza",
                "Chivatá",
                "Cómbita",
                "Cucaita",
                "Motavita",
                "Oicatá",
                "Samacá",
                "Siachoque",
                "Sora",
                "Soracá",
                "Sotaquirá",
                "Toca",
                "Tunja",
                "Tuta",
                "Ventaquemada",
                "Chiscas",
                "El Cocuy",
                "El Espino",
                "Guacamayas",
                "Güicán",
                "Panqueba",
                "Labranzagrande",
                "Pajarito",
                "Paya",
                "Pisba",
                "Berbeo",
                "Campohermoso",
                "Miraflores",
                "Páez",
                "San Eduardo",
                "Zetaquira",
                "Boyacá",
                "Ciénega",
                "Jenesano",
                "Nuevo Colón",
                "Ramiriquí",
                "Rondón",
                "Tibaná",
                "Turmequé",
                "Úmbita",
                "Viracachá",
                "Chinavita",
                "Garagoa",
                "Macanal",
                "Pachavita",
                "San Luis de Gaceno",
                "Santa María",
                "Boavita",
                "Covarachía",
                "La Uvita",
                "San Mateo",
                "Sativanorte",
                "Sativasur",
                "Soatá",
                "Susacón",
                "Tipacoque",
                "Briceño",
                "Buenavista",
                "Caldas",
                "Chiquinquirá",
                "Coper",
                "La Victoria",
                "Maripí",
                "Muzo",
                "Otanche",
                "Pauna",
                "Quípama",
                "Saboyá",
                "San Miguel de Sema",
                "San Pablo de Borbur",
                "Tununguá",
                "Almeida",
                "Chivor",
                "Guateque",
                "Guayatá",
                "La Capilla",
                "Somondoco",
                "Sutatenza",
                "Tenza",
                "Arcabuco",
                "Chitaraque",
                "Gachantivá",
                "Moniquirá",
                "Ráquira",
                "Sáchica",
                "San José de Pare",
                "Santa Sofía",
                "Santana",
                "Sutamarchán",
                "Tinjacá",
                "Togüí",
                "Villa de Leyva",
                "Aquitania",
                "Cuítiva",
                "Firavitoba",
                "Gámeza",
                "Iza",
                "Mongua",
                "Monguí",
                "Nobsa",
                "Pesca",
                "Sogamoso",
                "Tibasosa",
                "Tópaga",
                "Tota",
                "Belén",
                "Busbanzá",
                "Cerinza",
                "Corrales",
                "Duitama",
                "Floresta",
                "Paipa",
                "Santa Rosa de Viterbo",
                "Tutazá",
                "Betéitiva",
                "Chita",
                "Jericó",
                "Paz de Río",
                "Socha",
                "Socotá",
                "Tasco",
                "Cubará",
                "Puerto Boyacá"
            ]
        },
        {
            "id": 7,
            "nombre": "Caldas",
            "ciudades": [
                "Filadelfia",
                "La Merced",
                "Marmato",
                "Riosucio",
                "Supía",
                "Manzanares",
                "Marquetalia",
                "Marulanda",
                "Pensilvania",
                "Anserma",
                "Belalcázar",
                "Risaralda",
                "San José",
                "Viterbo",
                "Chinchiná",
                "Manizales",
                "Neira",
                "Palestina",
                "Villamaría",
                "La Dorada",
                "Norcasia",
                "Samaná",
                "Victoria",
                "Aguadas",
                "Aranzazu",
                "Pácora",
                "Salamina"
            ]
        },
        {
            "id": 8,
            "nombre": "Caquetá",
            "ciudades": [
                "Albania",
                "Belén de los Andaquíes",
                "Cartagena del Chairá",
                "Curillo",
                "El Doncello",
                "El Paujil",
                "Florencia",
                "La Montañita",
                "Milán",
                "Morelia",
                "Puerto Rico",
                "San José del Fragua",
                "San Vicente del Caguán",
                "Solano",
                "Solita",
                "Valparaíso"
            ]
        },
        {
            "id": 9,
            "nombre": "Casanare",
            "ciudades": [
                "Aguazul",
                "Chámeza",
                "Hato Corozal",
                "La Salina",
                "Maní",
                "Monterrey",
                "Nunchía",
                "Orocué",
                "Paz de Ariporo",
                "Pore",
                "Recetor",
                "Sabanalarga",
                "Sácama",
                "San Luis de Palenque",
                "Támara",
                "Tauramena",
                "Trinidad",
                "Villanueva",
                "Yopal"
            ]
        },
        {
            "id": 10,
            "nombre": "Cauca",
            "ciudades": [
                "Buenos Aires",
                "Caloto",
                "Corinto",
                "Guachené",
                "Miranda",
                "Padilla",
                "Puerto Tejada",
                "Santander de Quilichao",
                "Suárez",
                "Villa Rica",
                "Cajibío",
                "El Tambo",
                "La Sierra",
                "Morales",
                "Piendamó",
                "Popayán",
                "Rosas",
                "Sotará",
                "Timbío",
                "Almaguer",
                "Argelia",
                "Balboa",
                "Bolívar",
                "Florencia",
                "La Vega",
                "Mercaderes",
                "Patía",
                "Piamonte",
                "San Sebastián",
                "Santa Rosa",
                "Sucre",
                "Guapi",
                "López de Micay",
                "Timbiquí",
                "Caldono",
                "Inzá",
                "Jambaló",
                "Páez",
                "Puracé - Coconuco",
                "Silvia",
                "Toribío",
                "Totoró"
            ]
        },
        {
            "id": 11,
            "nombre": "Cesar",
            "ciudades": [
                "Valledupar",
                "Aguachica",
                "Agustín Codazzi",
                "Bosconia",
                "Chimichagua",
                "El Copey",
                "San Alberto",
                "Curumaní",
                "El Paso",
                "La Paz",
                "Pueblo Bello",
                "La Jagua de Ibirico",
                "Chiriguaná",
                "Astrea",
                "San Martín",
                "Pelaya",
                "Pailitas",
                "Gamarra",
                "Manaure",
                "Río de Oro",
                "Tamalameque",
                "Becerril",
                "San Diego",
                "La Gloria",
                "González"
            ]
        },
        {
            "id": 12,
            "nombre": "Chocó",
            "ciudades": [
                "Quibdó",
                "Acandí",
                "Alto Baudó",
                "Bagadó",
                "Bahía Solano",
                "Bajo Baudó",
                "Belén de Bajirá",
                "Bojayá",
                "Cértegui",
                "Condoto",
                "El Cantón de San Pablo",
                "El Carmen de Atrato",
                "El Litoral de San Juan",
                "Istmina",
                "Juradó",
                "Lloró",
                "Medio Atrato",
                "Medio Baudó",
                "Medio San Juan",
                "Nóvita",
                "Nuquí",
                "Río Iró",
                "Río Quito",
                "Riosucio",
                "San José del Palmar",
                "Sipí",
                "Tadó",
                "Unguía",
                "Unión Panamericana",
                "Nuevo Belén de Bajirá"
            ]
        },
        {
            "id": 13,
            "nombre": "Córdoba",
            "ciudades": [
                "Ayapel",
                "Buenavista",
                "Canalete",
                "Cereté",
                "Chimá",
                "Chinú",
                "Ciénaga de Oro",
                "Cotorra",
                "La Apartada",
                "Lorica",
                "Los Córdobas",
                "Momil",
                "Montelíbano",
                "Montería",
                "Moñitos",
                "Planeta Rica",
                "Pueblo Nuevo",
                "Puerto Escondido",
                "Puerto Libertador",
                "Purísima",
                "Sahagún",
                "San Andrés de Sotavento",
                "San Antero",
                "San Bernardo del Viento",
                "San Carlos",
                "San José de Uré",
                "San Pelayo",
                "Tierralta",
                "Tuchín",
                "Valencia",
                "Isla Fuerte"
            ]
        },
        {
            "id": 14,
            "nombre": "Cundinamarca",
            "ciudades": [
                "Agua de Dios",
                "Albán",
                "Anapoima",
                "Anolaima",
                "Apulo",
                "Arbeláez",
                "Beltrán",
                "Bituima",
                "Bojacá",
                "Cabrera",
                "Cachipay",
                "Cajicá",
                "Caparrapí",
                "Cáqueza",
                "Carmen de Carupa",
                "Chaguaní",
                "Chía",
                "Chipaque",
                "Choachí",
                "Chocontá",
                "Cogua",
                "Cota",
                "Cucunubá",
                "El Colegio",
                "El Peñón",
                "El Rosal",
                "Facatativá",
                "Fómeque",
                "Fosca",
                "Funza",
                "Fúquene",
                "Fusagasugá",
                "Gachalá",
                "Gachancipá",
                "Gachetá",
                "Gama",
                "Girardot",
                "Granada",
                "Guachetá",
                "Guaduas",
                "Guasca",
                "Guataquí",
                "Guatavita",
                "Guayabal de Síquima",
                "Guayabetal",
                "Gutiérrez",
                "Jerusalén",
                "Junín",
                "La Calera",
                "La Mesa",
                "La Palma",
                "La Peña",
                "La Vega",
                "Lenguazaque",
                "Machetá",
                "Madrid",
                "Manta",
                "Medina",
                "Mosquera",
                "Nariño",
                "Nemocón",
                "Nilo",
                "Nimaima",
                "Nocaima",
                "Pacho",
                "Paime",
                "Pandi",
                "Paratebueno",
                "Pasca",
                "Puerto Salgar",
                "Pulí",
                "Quebradanegra",
                "Quetame",
                "Quipile",
                "Ricaurte",
                "San Antonio del Tequendama",
                "San Bernardo",
                "San Cayetano",
                "San Francisco",
                "San Juan de Rioseco",
                "Sasaima",
                "Sesquilé",
                "Sibaté",
                "Silvania",
                "Simijaca",
                "Soacha",
                "Sopó",
                "Subachoque",
                "Suesca",
                "Supatá",
                "Susa",
                "Sutatausa",
                "Tabio",
                "Tausa",
                "Tena",
                "Tenjo",
                "Tibirita",
                "Tocaima",
                "Tocancipá",
                "Topaipí",
                "Ubalá",
                "Ubaque",
                "Ubaté",
                "Une",
                "Útica",
                "Venecia",
                "Vergara",
                "Vianí",
                "Villagómez",
                "Villapinzón",
                "Villeta",
                "Viotá",
                "Yacopí",
                "Zipacón",
                "Zipaquirá"
            ]
        },
        {
            "id": 15,
            "nombre": "Guainía",
            "ciudades": ["Inírida", "Barrancominas", "Cacahual", "La Guadalupe", "Morichal Nuevo", "Pana Pana", "Puerto Colombia", "San Felipe"]
        },
        { "id": 16, "nombre": "Guaviare", "ciudades": ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"] },
        {
            "id": 17,
            "nombre": "Huila",
            "ciudades": [
                "Acevedo",
                "Agrado",
                "Aipe",
                "Algeciras",
                "Altamira",
                "Baraya",
                "Campoalegre",
                "Colombia",
                "Elías",
                "Garzón",
                "Gigante",
                "Guadalupe",
                "Hobo",
                "Iquira",
                "Isnos",
                "La Argentina",
                "La Plata",
                "Nátaga",
                "Neiva",
                "Oporapa",
                "Paicol",
                "Palermo",
                "Palestina",
                "Pital",
                "Pitalito",
                "Rivera",
                "Saladoblanco",
                "San Agustín",
                "Santa María",
                "Suaza",
                "Tarqui",
                "Tello",
                "Teruel",
                "Tesalia",
                "Timaná",
                "Villavieja",
                "Yaguará"
            ]
        },
        {
            "id": 18,
            "nombre": "La Guajira",
            "ciudades": [
                "Albania",
                "Barrancas",
                "Dibulla",
                "Distracción",
                "El Molino",
                "Fonseca",
                "Hatonuevo",
                "La Jagua del Pilar",
                "Maicao",
                "Manaure",
                "Riohacha",
                "San Juan del Cesar",
                "Uribia",
                "Urumita",
                "Villanueva"
            ]
        },
        {
            "id": 19,
            "nombre": "Magdalena",
            "ciudades": [
                "Algarrobo",
                "Aracataca",
                "Ariguaní",
                "Cerro San Antonio",
                "Chibolo",
                "Ciénaga",
                "Concordia",
                "El Banco",
                "El Piñón",
                "El Retén",
                "Fundación",
                "Guamal",
                "Nueva Granada",
                "Pedraza",
                "Pijiño del Carmen",
                "Pivijay",
                "Plato",
                "Puebloviejo",
                "Remolino",
                "Sabanas de San Ángel",
                "Salamina",
                "San Sebastián de Buenavista",
                "San Zenón",
                "Santa Ana",
                "Santa Bárbara de Pinto",
                "Santa Marta",
                "Sitionuevo",
                "Tenerife",
                "Zapayán",
                "Zona Bananera"
            ]
        },
        {
            "id": 20,
            "nombre": "Meta",
            "ciudades": [
                "Acacías",
                "Barranca de Upía",
                "Cabuyaro",
                "Castilla la Nueva",
                "Cubarral",
                "Cumaral",
                "El Calvario",
                "El Castillo",
                "El Dorado",
                "Fuente de Oro",
                "Granada",
                "Guamal",
                "La Macarena",
                "Lejanías",
                "Mapiripán",
                "Mesetas",
                "La Uribe",
                "Puerto Concordia",
                "Puerto Gaitán",
                "Puerto Lleras",
                "Puerto López",
                "Puerto Rico",
                "Restrepo",
                "San Carlos de Guaroa",
                "San Juan de Arama",
                "San Juanito",
                "San Martín",
                "Villavicencio",
                "Vista Hermosa"
            ]
        },
        {
            "id": 21,
            "nombre": "Nariño",
            "ciudades": [
                "Albán",
                "Aldana",
                "Ancuya",
                "Arboleda",
                "Barbacoas",
                "Belén",
                "Buesaco",
                "Chachagüí",
                "Colón",
                "Consacá",
                "Contadero",
                "Córdoba",
                "Cuaspud",
                "Cumbal",
                "Cumbitara",
                "El Charco",
                "El Peñol",
                "El Rosario",
                "El Tablón",
                "El Tambo",
                "Francisco Pizarro",
                "Funes",
                "Guachucal",
                "Guaitarilla",
                "Gualmatán",
                "Iles",
                "Imués",
                "Ipiales",
                "La Cruz",
                "La Florida",
                "La Llanada",
                "La Tola",
                "La Unión",
                "Leiva",
                "Linares",
                "Los Andes",
                "Magüi",
                "Mallama",
                "Mosquera",
                "Nariño",
                "Olaya Herrera",
                "Ospina",
                "Pasto",
                "Policarpa",
                "Potosí",
                "Providencia",
                "Puerres",
                "Pupiales",
                "Ricaurte",
                "Roberto Payán",
                "Samaniego",
                "San Bernardo",
                "San Lorenzo",
                "San Pablo",
                "San Pedro de Cartago",
                "Sandoná",
                "Santa Bárbara",
                "Santacruz",
                "Sapuyes",
                "Taminango",
                "Tangua",
                "Tumaco",
                "Túquerres",
                "Yacuanquer"
            ]
        },
        {
            "id": 22,
            "nombre": "Norte de Santander",
            "ciudades": [
                "Abrego",
                "Arboledas",
                "Bochalema",
                "Bucarasica",
                "Cáchira",
                "Cácota",
                "Chinácota",
                "Chitagá",
                "Convención",
                "Cúcuta",
                "Cucutilla",
                "Durania",
                "El Carmen",
                "El Tarra",
                "El Zulia",
                "Gramalote",
                "Hacarí",
                "Herrán",
                "La Esperanza",
                "La Playa",
                "Labateca",
                "Los Patios",
                "Lourdes",
                "Mutiscua",
                "Ocaña",
                "Pamplona",
                "Pamplonita",
                "Puerto Santander",
                "Ragonvalia",
                "Salazar de Las Palmas",
                "San Calixto",
                "San Cayetano",
                "Santiago",
                "Sardinata",
                "Silos",
                "Teorama",
                "Tibú",
                "Toledo",
                "Villa Caro",
                "Villa del Rosario"
            ]
        },
        {
            "id": 23,
            "nombre": "Putumayo",
            "ciudades": [
                "Colón",
                "Mocoa",
                "Orito",
                "Puerto Asís",
                "Puerto Caicedo",
                "Puerto Guzmán",
                "Puerto Leguízamo",
                "Sibundoy",
                "San Francisco",
                "San Miguel",
                "Santiago",
                "Villagarzón"
            ]
        },
        {
            "id": 24,
            "nombre": "Quindío",
            "ciudades": [
                "Armenia",
                "Buenavista",
                "Calarcá",
                "Circasia",
                "Córdoba",
                "Filandia",
                "Génova",
                "La Tebaida",
                "Montenegro",
                "Pijao",
                "Quimbaya",
                "Salento"
            ]
        },
        {
            "id": 25,
            "nombre": "Risaralda",
            "ciudades": [
                "Apía",
                "Balboa",
                "Belén de Umbría",
                "Dosquebradas",
                "Guática",
                "La Celia",
                "La Virginia",
                "Marsella",
                "Mistrató",
                "Pereira",
                "Pueblo Rico",
                "Quinchía",
                "Santa Rosa de Cabal",
                "Santuario"
            ]
        },
        { "id": 26, "nombre": "San Andrés y Providencia", "ciudades": ["Providencia", "San Andrés"] },
        {
            "id": 27,
            "nombre": "Santander",
            "ciudades": [
                "Aguada",
                "Albania",
                "Aratoca",
                "Barbosa",
                "Barichara",
                "Barrancabermeja",
                "Betulia",
                "Bolívar",
                "Bucaramanga",
                "Cabrera",
                "California",
                "Capitanejo",
                "Carcasí",
                "Cepitá",
                "Cerrito",
                "Charalá",
                "Charta",
                "Chima",
                "Chipatá",
                "Cimitarra",
                "Concepción",
                "Confines",
                "Contratación",
                "Coromoro",
                "Curití",
                "El Carmen de Chucurí",
                "El Guacamayo",
                "El Peñón",
                "El Playón",
                "Encino",
                "Enciso",
                "Florián",
                "Floridablanca",
                "Galán",
                "Gambita",
                "Girón",
                "Guaca",
                "Guadalupe",
                "Guapotá",
                "Guavatá",
                "Güepsa",
                "Hato",
                "Jesús María",
                "Jordán",
                "La Belleza",
                "Landázuri",
                "La Paz",
                "Lebrija",
                "Los Santos",
                "Macaravita",
                "Málaga",
                "Matanza",
                "Mogotes",
                "Molagavita",
                "Ocamonte",
                "Oiba",
                "Onzaga",
                "Palmar",
                "Palmas del Socorro",
                "Páramo",
                "Piedecuesta",
                "Pinchote",
                "Puente Nacional",
                "Puerto Parra",
                "Puerto Wilches",
                "Rionegro",
                "Sabana de Torres",
                "San Andrés",
                "San Benito",
                "San Gil",
                "San Joaquín",
                "San José de Miranda",
                "San Miguel",
                "San Vicente de Chucurí",
                "Santa Bárbara",
                "Santa Helena del Opón",
                "Simacota",
                "Suaita",
                "Sucre",
                "Suratá",
                "Tona",
                "Valle de San José",
                "Vélez",
                "Vetas",
                "Villanueva",
                "Zapatoca"
            ]
        },
        {
            "id": 28,
            "nombre": "Sucre",
            "ciudades": [
                "Buenavista",
                "Caimito",
                "Chalán",
                "Colosó",
                "Corozal",
                "Coveñas",
                "El Roble",
                "Galeras",
                "Guaranda",
                "La Unión",
                "Los Palmitos",
                "Majagual",
                "Morroa",
                "Ovejas",
                "Palmito",
                "Sampués",
                "San Benito Abad",
                "San Juan de Betulia",
                "San Marcos",
                "San Onofre",
                "San Pedro",
                "Sincé",
                "Sincelejo",
                "Sucre",
                "Tolú",
                "Toluviejo"
            ]
        },
        {
            "id": 29,
            "nombre": "Tolima",
            "ciudades": [
                "Alpujarra",
                "Alvarado",
                "Ambalema",
                "Anzoátegui",
                "Armero",
                "Ataco",
                "Cajamarca",
                "Carmen de Apicalá",
                "Casabianca",
                "Chaparral",
                "Coello",
                "Coyaima",
                "Cunday",
                "Dolores",
                "Espinal",
                "Falan",
                "Flandes",
                "Fresno",
                "Guamo",
                "Herveo",
                "Honda",
                "Ibagué",
                "Icononzo",
                "Lérida",
                "Líbano",
                "Mariquita",
                "Melgar",
                "Murillo",
                "Natagaima",
                "Ortega",
                "Palocabildo",
                "Piedras",
                "Planadas",
                "Prado",
                "Purificación",
                "Rioblanco",
                "Roncesvalles",
                "Rovira",
                "Saldaña",
                "San Antonio",
                "San Luis",
                "Santa Isabel",
                "Suárez",
                "Valle de San Juan",
                "Venadillo",
                "Villahermosa",
                "Villarrica"
            ]
        },
        {
            "id": 30,
            "nombre": "Valle del Cauca",
            "ciudades": [
                "Alcalá",
                "Andalucía",
                "Ansermanuevo",
                "Bolívar",
                "Buga",
                "Bugalagrande",
                "Caicedonia",
                "Cali",
                "Candelaria",
                "Cartago",
                "Dagua",
                "El Águila",
                "El Cairo",
                "El Cerrito",
                "El Dovio",
                "Florida",
                "Ginebra",
                "Guacarí",
                "Jamundí",
                "La Cumbre",
                "La Unión",
                "La Victoria",
                "Obando",
                "Palmira",
                "Pradera",
                "Restrepo",
                "Riofrío",
                "Roldanillo",
                "San Pedro",
                "Sevilla",
                "Toro",
                "Trujillo",
                "Tuluá",
                "Ulloa",
                "Versalles",
                "Vijes",
                "Yotoco",
                "Yumbo",
                "Zarzal"
            ]
        },
        { "id": 31, "nombre": "Vaupés", "ciudades": ["Carurú", "Mitú", "Taraira", "Pacoa", "Yavaraté"] },
        { "id": 32, "nombre": "Vichada", "ciudades": ["Cumaribo", "La Primavera", "Puerto Carreño", "Santa Rosalía"] },
        { "id": 33, "nombre": "Bogotá", "ciudades": ["Bogotá D.C."] }
    ]
}
