import flet as ft

class CountryDropdown(ft.Dropdown):
    def __init__(self, on_country_change=None):
        # Usamos los mismos parámetros que "department_dropdown"/"city_dropdown".
        super().__init__(
            border_radius=ft.border_radius.all(15),
            content_padding=ft.padding.symmetric(horizontal=20, vertical=15),
            bgcolor=ft.Colors.WHITE,
            border_color="#717171",
            label_style=ft.TextStyle(color="#717171"),
            border_width=0.5,
            options=[],                
            on_change=self.handle_country_change,
        )
        self.on_country_change = on_country_change

        # Cargamos las opciones de país
        self.options = self._get_country_options()

    def _get_country_options(self):
        """Crea las opciones del dropdown con banderas y nombres de países."""
        country_data = {
            "Afganistán": {"flag": "flags/af.png"},
            "Albania": {"flag": "flags/al.png"},
            "Argelia": {"flag": "flags/dz.png"},
            "Andorra": {"flag": "flags/ad.png"},
            "Angola": {"flag": "flags/ao.png"},
            "Antigua y Barbuda": {"flag": "flags/ag.png"},
            "Argentina": {"flag": "flags/ar.png"},
            "Armenia": {"flag": "flags/am.png"},
            "Australia": {"flag": "flags/au.png"},
            "Austria": {"flag": "flags/at.png"},
            "Azerbaiyán": {"flag": "flags/az.png"},
            "Bahamas": {"flag": "flags/bs.png"},
            "Baréin": {"flag": "flags/bh.png"},
            "Bangladés": {"flag": "flags/bd.png"},
            "Barbados": {"flag": "flags/bb.png"},
            "Bielorrusia": {"flag": "flags/by.png"},
            "Bélgica": {"flag": "flags/be.png"},
            "Belice": {"flag": "flags/bz.png"},
            "Benín": {"flag": "flags/bj.png"},
            "Bután": {"flag": "flags/bt.png"},
            "Bolivia": {"flag": "flags/bo.png"},
            "Bosnia y Herzegovina": {"flag": "flags/ba.png"},
            "Botsuana": {"flag": "flags/bw.png"},
            "Brasil": {"flag": "flags/br.png"},
            "Brunéi": {"flag": "flags/bn.png"},
            "Bulgaria": {"flag": "flags/bg.png"},
            "Burkina Faso": {"flag": "flags/bf.png"},
            "Burundi": {"flag": "flags/bi.png"},
            "Camboya": {"flag": "flags/kh.png"},
            "Camerún": {"flag": "flags/cm.png"},
            "Canadá": {"flag": "flags/ca.png"},
            "Cabo Verde": {"flag": "flags/cv.png"},
            "República Centroafricana": {"flag": "flags/cf.png"},
            "Chad": {"flag": "flags/td.png"},
            "Chile": {"flag": "flags/cl.png"},
            "China": {"flag": "flags/cn.png"},
            "Colombia": {"flag": "flags/co.png"},
            "Comoras": {"flag": "flags/km.png"},
            "Congo (Brazzaville)": {"flag": "flags/cg.png"},
            "Congo (Kinshasa)": {"flag": "flags/cd.png"},
            "Costa Rica": {"flag": "flags/cr.png"},
            "Croacia": {"flag": "flags/hr.png"},
            "Cuba": {"flag": "flags/cu.png"},
            "Chipre": {"flag": "flags/cy.png"},
            "República Checa": {"flag": "flags/cz.png"},
            "Dinamarca": {"flag": "flags/dk.png"},
            "Yibuti": {"flag": "flags/dj.png"},
            "Dominica": {"flag": "flags/dm.png"},
            "República Dominicana": {"flag": "flags/do.png"},
            "Ecuador": {"flag": "flags/ec.png"},
            "Egipto": {"flag": "flags/eg.png"},
            "El Salvador": {"flag": "flags/sv.png"},
            "Guinea Ecuatorial": {"flag": "flags/gq.png"},
            "Eritrea": {"flag": "flags/er.png"},
            "Estonia": {"flag": "flags/ee.png"},
            "Esuatini": {"flag": "flags/sz.png"},
            "Etiopía": {"flag": "flags/et.png"},
            "Fiyi": {"flag": "flags/fj.png"},
            "Finlandia": {"flag": "flags/fi.png"},
            "Francia": {"flag": "flags/fr.png"},
            "Gabón": {"flag": "flags/ga.png"},
            "Gambia": {"flag": "flags/gm.png"},
            "Georgia": {"flag": "flags/ge.png"},
            "Alemania": {"flag": "flags/de.png"},
            "Ghana": {"flag": "flags/gh.png"},
            "Grecia": {"flag": "flags/gr.png"},
            "Granada": {"flag": "flags/gd.png"},
            "Guatemala": {"flag": "flags/gt.png"},
            "Guinea": {"flag": "flags/gn.png"},
            "Guinea-Bisáu": {"flag": "flags/gw.png"},
            "Guyana": {"flag": "flags/gy.png"},
            "Haití": {"flag": "flags/ht.png"},
            "Honduras": {"flag": "flags/hn.png"},
            "Hungría": {"flag": "flags/hu.png"},
            "Islandia": {"flag": "flags/is.png"},
            "India": {"flag": "flags/in.png"},
            "Indonesia": {"flag": "flags/id.png"},
            "Irán": {"flag": "flags/ir.png"},
            "Irak": {"flag": "flags/iq.png"},
            "Irlanda": {"flag": "flags/ie.png"},
            "Israel": {"flag": "flags/il.png"},
            "Italia": {"flag": "flags/it.png"},
            "Jamaica": {"flag": "flags/jm.png"},
            "Japón": {"flag": "flags/jp.png"},
            "Jordania": {"flag": "flags/jo.png"},
            "Kazajistán": {"flag": "flags/kz.png"},
            "Kenia": {"flag": "flags/ke.png"},
            "Kiribati": {"flag": "flags/ki.png"},
            "Kuwait": {"flag": "flags/kw.png"},
            "Kirguistán": {"flag": "flags/kg.png"},
            "Laos": {"flag": "flags/la.png"},
            "Letonia": {"flag": "flags/lv.png"},
            "Líbano": {"flag": "flags/lb.png"},
            "Lesoto": {"flag": "flags/ls.png"},
            "Liberia": {"flag": "flags/lr.png"},
            "Libia": {"flag": "flags/ly.png"},
            "Liechtenstein": {"flag": "flags/li.png"},
            "Lituania": {"flag": "flags/lt.png"},
            "Luxemburgo": {"flag": "flags/lu.png"},
            "Madagascar": {"flag": "flags/mg.png"},
            "Malaui": {"flag": "flags/mw.png"},
            "Malasia": {"flag": "flags/my.png"},
            "Maldivas": {"flag": "flags/mv.png"},
            "Malí": {"flag": "flags/ml.png"},
            "Malta": {"flag": "flags/mt.png"},
            "Islas Marshall": {"flag": "flags/mh.png"},
            "Mauritania": {"flag": "flags/mr.png"},
            "Mauricio": {"flag": "flags/mu.png"},
            "México": {"flag": "flags/mx.png"},
            "Micronesia": {"flag": "flags/fm.png"},
            "Moldavia": {"flag": "flags/md.png"},
            "Mónaco": {"flag": "flags/mc.png"},
            "Mongolia": {"flag": "flags/mn.png"},
            "Montenegro": {"flag": "flags/me.png"},
            "Marruecos": {"flag": "flags/ma.png"},
            "Mozambique": {"flag": "flags/mz.png"},
            "Birmania": {"flag": "flags/mm.png"},
            "Namibia": {"flag": "flags/na.png"},
            "Nauru": {"flag": "flags/nr.png"},
            "Nepal": {"flag": "flags/np.png"},
            "Países Bajos": {"flag": "flags/nl.png"},
            "Nueva Zelanda": {"flag": "flags/nz.png"},
            "Nicaragua": {"flag": "flags/ni.png"},
            "Níger": {"flag": "flags/ne.png"},
            "Nigeria": {"flag": "flags/ng.png"},
            "Corea del Norte": {"flag": "flags/kp.png"},
            "Macedonia del Norte": {"flag": "flags/mk.png"},
            "Noruega": {"flag": "flags/no.png"},
            "Omán": {"flag": "flags/om.png"},
            "Pakistán": {"flag": "flags/pk.png"},
            "Palaos": {"flag": "flags/pw.png"},
            "Palestina": {"flag": "flags/ps.png"},
            "Panamá": {"flag": "flags/pa.png"},
            "Papúa Nueva Guinea": {"flag": "flags/pg.png"},
            "Paraguay": {"flag": "flags/py.png"},
            "Perú": {"flag": "flags/pe.png"},
            "Filipinas": {"flag": "flags/ph.png"},
            "Polonia": {"flag": "flags/pl.png"},
            "Portugal": {"flag": "flags/pt.png"},
            "Catar": {"flag": "flags/qa.png"},
            "Rumania": {"flag": "flags/ro.png"},
            "Rusia": {"flag": "flags/ru.png"},
            "Ruanda": {"flag": "flags/rw.png"},
            "San Cristóbal y Nieves": {"flag": "flags/kn.png"},
            "Santa Lucía": {"flag": "flags/lc.png"},
            "San Vicente y las Granadinas": {"flag": "flags/vc.png"},
            "Samoa": {"flag": "flags/ws.png"},
            "San Marino": {"flag": "flags/sm.png"},
            "Santo Tomé y Príncipe": {"flag": "flags/st.png"},
            "Arabia Saudita": {"flag": "flags/sa.png"},
            "Senegal": {"flag": "flags/sn.png"},
            "Serbia": {"flag": "flags/rs.png"},
            "Seychelles": {"flag": "flags/sc.png"},
            "Sierra Leona": {"flag": "flags/sl.png"},
            "Singapur": {"flag": "flags/sg.png"},
            "Eslovaquia": {"flag": "flags/sk.png"},
            "Eslovenia": {"flag": "flags/si.png"},
            "Islas Salomón": {"flag": "flags/sb.png"},
            "Somalia": {"flag": "flags/so.png"},
            "Sudáfrica": {"flag": "flags/za.png"},
            "Corea del Sur": {"flag": "flags/kr.png"},
            "Sudán del Sur": {"flag": "flags/ss.png"},
            "España": {"flag": "flags/es.png"},
            "Sri Lanka": {"flag": "flags/lk.png"},
            "Sudán": {"flag": "flags/sd.png"},
            "Surinam": {"flag": "flags/sr.png"},
            "Suecia": {"flag": "flags/se.png"},
            "Suiza": {"flag": "flags/ch.png"},
            "Siria": {"flag": "flags/sy.png"},
            "Taiwán": {"flag": "flags/tw.png"},
            "Tayikistán": {"flag": "flags/tj.png"},
            "Tanzania": {"flag": "flags/tz.png"},
            "Tailandia": {"flag": "flags/th.png"},
            "Timor Oriental": {"flag": "flags/tl.png"},
            "Togo": {"flag": "flags/tg.png"},
            "Tonga": {"flag": "flags/to.png"},
            "Trinidad y Tobago": {"flag": "flags/tt.png"},
            "Túnez": {"flag": "flags/tn.png"},
            "Turquía": {"flag": "flags/tr.png"},
            "Turkmenistán": {"flag": "flags/tm.png"},
            "Tuvalu": {"flag": "flags/tv.png"},
            "Uganda": {"flag": "flags/ug.png"},
            "Ucrania": {"flag": "flags/ua.png"},
            "Emiratos Árabes Unidos": {"flag": "flags/ae.png"},
            "Reino Unido": {"flag": "flags/gb.png"},
            "Estados Unidos": {"flag": "flags/us.png"},
            "Uruguay": {"flag": "flags/uy.png"},
            "Uzbekistán": {"flag": "flags/uz.png"},
            "Vanuatu": {"flag": "flags/vu.png"},
            "Ciudad del Vaticano": {"flag": "flags/va.png"},
            "Venezuela": {"flag": "flags/ve.png"},
            "Vietnam": {"flag": "flags/vn.png"},
            "Yemen": {"flag": "flags/ye.png"},
            "Zambia": {"flag": "flags/zm.png"},
            "Zimbabue": {"flag": "flags/zw.png"}
        }

        return [
            ft.dropdown.Option(
                key=country_name,
                content=ft.Row(
                    controls=[
                        ft.Image(src=country_info["flag"], width=20, height=20),
                        ft.Text(country_name, size=14, color=ft.Colors.BLACK),
                    ],
                    alignment=ft.MainAxisAlignment.START,
                ),
            )
            for country_name, country_info in country_data.items()
        ]

    def handle_country_change(self, e):
        """Callback para manejar el cambio de país."""
        if self.on_country_change:
            self.on_country_change(e.control.value)
